[package]
name = "panic"
version = "0.1.0"
authors = ["Jeff van Geete <jeff.vangeete@protectwise.com>"]
edition = "2018"

[dependencies]

# save space by preventing panic / stack unwind. instead: abort
# [profile.release]
# panic = 'abort'